import { type Story } from "@/components/StoryItem";

export const topStories: Story[] = [
  {
    id: 1,
    title: "ACL Pro Tour Kicks Off in Austin with Record Crowd and Big Plays",
    url: "https://acltour.com",
    domain: "acltour.com",
    points: 142,
    author: "bag_toss_pro",
    timeAgo: "2 hours ago",
    commentCount: 38,
  },
  {
    id: 2,
    title: "New Study: The Physics Behind the Perfect Slide",
    url: "https://cornholescience.org",
    domain: "cornholescience.org",
    points: 89,
    author: "slideright",
    timeAgo: "4 hours ago",
    commentCount: 21,
  },
  {
    id: 3,
    title: "ACL World Championships 2025 – Day 2 Recap",
    url: "https://aclprocornhole.com",
    domain: "aclprocornhole.com",
    points: 76,
    author: "cornholefanatic",
    timeAgo: "6 hours ago",
    commentCount: 15,
  },
  {
    id: 4,
    title: "Building the Ultimate Cornhole Board: A DIY Guide",
    url: "https://yardgamecrafts.com",
    domain: "yardgamecrafts.com",
    points: 63,
    author: "woodworker415",
    timeAgo: "8 hours ago",
    commentCount: 17,
  },
  {
    id: 5,
    title: "Top 10 Cornhole Bags of 2025 – Buyer's Guide",
    url: "https://cornolereviewhub.com",
    domain: "cornolereviewhub.com",
    points: 54,
    author: "tossboss",
    timeAgo: "10 hours ago",
    commentCount: 12,
  },
  {
    id: 6,
    title: "Local League Spotlight: Midwest Cornhole Circuit",
    url: "https://midwestcornholecircuit.com",
    domain: "midwestcornholecircuit.com",
    points: 41,
    author: "cornholelover",
    timeAgo: "12 hours ago",
    commentCount: 9,
  },
  {
    id: 7,
    title: "Cornhole Etiquette: Dos and Don'ts at the Boards",
    url: "https://cornhole101.com",
    domain: "cornhole101.com",
    points: 33,
    author: "chilltoss",
    timeAgo: "14 hours ago",
    commentCount: 7,
  },
  {
    id: 8,
    title: "How to Host a Successful Cornhole Tournament",
    url: "https://hostcornhole.com",
    domain: "hostcornhole.com",
    points: 28,
    author: "eventmaster",
    timeAgo: "16 hours ago",
    commentCount: 6,
  },
  {
    id: 9,
    title: "Video: Insane Comeback Shot from Last Weekend",
    url: "https://youtube.com",
    domain: "youtube.com",
    points: 25,
    author: "highlightreel",
    timeAgo: "18 hours ago",
    commentCount: 5,
  },
  {
    id: 10,
    title: "Cornhole Gear on a Budget: Under $50",
    url: "https://budgetbags.com",
    domain: "budgetbags.com",
    points: 19,
    author: "frugaltosser",
    timeAgo: "20 hours ago",
    commentCount: 4,
  },
];

export const newStories: Story[] = [
  {
    id: 11,
    title: "Ask CN: Best bags for outdoor windy conditions?",
    points: 12,
    author: "windytoss",
    timeAgo: "45 minutes ago",
    commentCount: 8,
  },
  {
    id: 12,
    title: "Just finished my first regulation board – photos inside",
    url: "https://imgur.com",
    domain: "imgur.com",
    points: 9,
    author: "newbuilder",
    timeAgo: "1 hour ago",
    commentCount: 3,
  },
  {
    id: 13,
    title: "Anyone else notice the new ACL rule changes?",
    points: 7,
    author: "rulewatcher",
    timeAgo: "2 hours ago",
    commentCount: 11,
  },
];
